version: '3.8'
services:
  db:
    image: postgres:13.2
    ports:
      - 5449:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: recommender
    volumes:
      - db-data:/var/lib/postgresql/data:rw
  php:
    build:
      context: ./docker/php
    volumes:
      - .:/var/www/recommender:delegated
    links:
      - db
    environment:
      DATABASE_URL: "postgresql://root:root@db:5432/recommender"
      APP_URL: "http://recommender.local:8099"
      APP_ENV: "dev"
      APP_SECRET: "9741dcf383ef9d07f9fbf17e202d2969"
      APP_HOSTNAME: "recommender.local"
  nginx:
    image: nginx:1.19
    ports:
      - "8099:80"
    volumes:
      - .:/var/www/recommender:delegated
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - php
volumes:
  db-data: